name: instagram_clone
description: Final Project

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  # for image
  image_picker: ^0.8.6
  cached_network_image: ^3.2.2

  # format
  intl: ^0.17.0

  # storage
  shared_preferences: ^2.0.15

  # firebase
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.2
  firebase_messaging: ^13.1.0
  cloud_firestore: ^3.5.1
  firebase_storage: ^10.3.11

  # notification
  flutter_local_notifications: ^12.0.1+1

  # device info
  device_info_plus: ^5.0.5

  # network
  http: ^0.13.5
  data_connection_checker_nulls: ^0.0.2

  # objects equals
  equatable: ^2.0.5

  # test
  mockito: ^5.3.2

  # service locator
  get_it: ^7.2.0

  # state management
  flutter_bloc: ^8.1.1

  # Functional programming thingies
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # for generate class
  build_runner: ^2.2.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf